const crcPayload = {
  "origem":"CRC",
  "ID_TP_PROC_E":1,
  "ID_T_PES_E":"", 
  "ID_CPF_CNPJ_E":"",
  "ID_USR_INC_E":"",
  "W115E_LST_PARM":[
     {
        "ID_ETAP_PRPT_E":2,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":3,
        "ID_T_VLDC_E":2,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":4,
        "ID_T_VLDC_E":2,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":5,
        "ID_T_VLDC_E":2,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":6,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":7,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":8,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":9,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":10,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":11,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":12,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":13,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"I"
     },
     {
        "ID_ETAP_PRPT_E":14,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"I"
     },
     {
        "ID_ETAP_PRPT_E":15,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":16,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"I"
     },
     {
        "ID_ETAP_PRPT_E":17,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"I"
     },
     {
        "ID_ETAP_PRPT_E":18,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":19,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":20,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"I"
     },
     {
        "ID_ETAP_PRPT_E":21,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":22,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":23,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":24,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":25,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":26,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":27,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":28,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":81,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":82,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":83,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":84,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":85,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":86,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":87,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":88,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     },
     {
        "ID_ETAP_PRPT_E":89,
        "ID_T_VLDC_E":1,
        "IC_SIT_PARM_E":"A"
     }
  ],
  "W115E_LST_OCORR":[
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     },
     {
        "ID_ETAP_PRPT_OE":"",
        "ID_STAT_OCRC_E":"",
        "IC_APAO_EXCE_E":"",
        "DT_APAO_E":"",
        "ID_USR_APAO_E":""
     }
  ],
  "W115S_LST_SOCIOS":[
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     },
     {
        "W115_ID_NUM_SOC_E":"",
        "W115_TIPO_PES_E":"",
        "W115S_CPF_CNPJ":""
     }
  ]
}
export = crcPayload;